### get all users
GET http://localhost:3000/api/user
Accept: application/json


### Create new user
POST http://localhost:3000/api/user
Content-Type: application/json

{
  "username": "new user"
}


### Update existing user
PUT http://localhost:3000/api/user/2
Content-Type: application/json

{
  "username": "changed name",
  "id": 2
}


### get user with specific id
GET http://localhost:3000/api/user/2
Accept: application/json


### delete user with specific id
DELETE http://localhost:3000/api/user/2
Accept: application/json
